version: "3.9"

services:
  web:
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env.local
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./app/postgres/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"